### ISSUE TITLE
个人学习

### ISSUE THREAD

**Issue by ay061** [royeo/awesome-programming-books#11]
可以私发一份给我学习使用吗？谢谢
ayue061@outlook.com

**Comment by chenkang084** [comment]
@ay061 github是分布式的，主仓库删了，是没有彻底删除的。你去fork里面，随便找一个别人fork的仓库就可以了。你也可以基于这个仓库，再fork自己的仓库。

**Comment by ay061** [comment]
好的，感谢感谢
