### ISSUE TITLE
为什么全是404

### ISSUE THREAD

**Issue by zhang-wenfu** [royeo/awesome-programming-books#13]
相关的pdf还能获取到吗

**Comment by chenkuojun** [comment]
我是直接fork 别人的，别人要是删除了估计就没有了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "royeo/awesome-programming-books"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 中午11:33
收件人:&nbsp;"royeo/awesome-programming-books"<awesome-programming-books@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[royeo/awesome-programming-books] 为什么全是404 (#13)





 
相关的pdf还能获取到吗

**Comment by zhang-wenfu** [comment]
好的，我再去别处找找。谢了

**Comment by zhang-wenfu** [comment]
好吧，我再去别处找找。谢谢了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "royeo/awesome-programming-books"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 中午11:35
收件人:&nbsp;"royeo/awesome-programming-books"<awesome-programming-books@noreply.github.com&gt;;
抄送:&nbsp;"羽落  "<1152792860@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [royeo/awesome-programming-books] 为什么全是404 (#13)





 我是直接fork 别人的，别人要是删除了估计就没有了 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "royeo/awesome-programming-books"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月28日(星期二) 中午11:33 
 收件人:&amp;nbsp;"royeo/awesome-programming-books"<awesome-programming-books@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[royeo/awesome-programming-books] 为什么全是404 (#13) 
 
 
 
 
 
   
 相关的pdf还能获取到吗
